analyzer:
  strong-mode: true
linter:
  rules:
    - always_declare_return_types
    - camel_case_types
    - iterable_contains_unrelated_type
    - hash_and_equals
    - empty_constructor_bodies
    - annotate_overrides
    - avoid_init_to_null
    - constant_identifier_names
    - one_member_abstracts
    - slash_for_doc_comments
    - sort_constructors_first
    - unnecessary_brace_in_string_interp
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
