name: dcache
version: 0.2.0
author: Kevin PLATEL <platel.kevin@gmail.com>
description: >
  Provide a simple dart cache library usable on client and server side
homepage: https://github.com/platelk/dcache
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  meta: '^1.1.7'
dev_dependencies:
  test: '^1.5.1'
  pedantic: '^1.4.0'
