name: dcache
version: 0.0.1
author: Kevin PLATEL <platel.kevin@gmail.com>
description: >
  Provide a simple dart cache library usable on client and server side
dependencies:
  meta: any
dev_dependencies:
  test: any
